function Filters()

fig=findall(0,'type','figure'); %find all figures
delete(fig); %delete all figures

figure1 = figure('Visible','on','Position', [2000 200 1175 500],'color','white');

%this panle will hold the switch matrix and DUT relevant info.
hLPHP   = uipanel('units','pixels','visible','on','Title',...
                       'LP & HP equations',...
                       'FontSize',16,'backgroundcolor','white',...
                       'fontweight','bold','Position',[211,300,152,165]);

%create axis for DUT matrix image
hLPHPImage   = axes('parent',hLPHP,'Units','pixels',...
                     'Position',[10,10,120,120]);
                     visual=imread('LP_HP.png'); %read in image
                     image(visual); %set image into axis
                     set(gca,'XTick',[]) %remove tick marks
                     set(gca,'YTick',[])
                     
hPrototypeValue  = uicontrol('Parent',figure1,'Style','edit','Position',...
                      [15 402 144 25],'string','',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hPrototypeValuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [20 428 131 25],'string','Prototype Value',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hRValue  = uicontrol('Parent',figure1,'Style','edit','Position',...
                      [15 345 144 25],'string','',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hRValuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [20 370 131 25],'string','Rload',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hcutoff_fValue  = uicontrol('Parent',figure1,'Style','edit','Position',...
                      [15 295 144 25],'string','',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hcutoff_fValuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [20 320 131 25],'string','Cut-off f',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hLPHPCalc  = uicontrol('Parent',figure1,'Style','pushbutton','Position',...
                      [20 265 131 25],'string','Calculate',...
                     'backgroundcolor','g','fontsize',13,'enable','on',...
                     'foregroundcolor','k','callback',@CalculateLPHP);
                 
hC1Valuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [160 265 131 25],'string','C=',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hL1Valuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [160 240 131 25],'string','L=',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
 
                 
                 
                 
                 
                 
%this panle will hold the switch matrix and DUT relevant info.
hBPP   = uipanel('units','pixels','visible','on','Title',...
                       'BP Parralel equations',...
                       'FontSize',16,'backgroundcolor','white',...
                       'fontweight','bold','Position',[637,293,152,165]);

%create axis for DUT matrix image
hBPPImage   = axes('parent',hBPP,'Units','pixels',...
                     'Position',[10,10,120,120]);
                     visual=imread('BP_Parallel.png'); %read in image
                     image(visual); %set image into axis
                     set(gca,'XTick',[]) %remove tick marks
                     set(gca,'YTick',[])
                     
%this panle will hold the switch matrix and DUT relevant info.
hBPS   = uipanel('units','pixels','visible','on','Title',...
                       'BP Series equations',...
                       'FontSize',16,'backgroundcolor','white',...
                       'fontweight','bold','Position',[895,293,152,165]);

%create axis for DUT matrix image
hBPSImage   = axes('parent',hBPS,'Units','pixels',...
                     'Position',[10,10,120,120]);
                     visual=imread('BP_Series.png'); %read in image
                     image(visual); %set image into axis
                     set(gca,'XTick',[]) %remove tick marks
                     set(gca,'YTick',[])
                     
hBPPrototypeValue  = uicontrol('Parent',figure1,'Style','edit','Position',...
                      [455 402 144 25],'string','',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPPrototypeValuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [455 428 131 25],'string','Prototype Value',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPRValue  = uicontrol('Parent',figure1,'Style','edit','Position',...
                      [455 345 144 25],'string','',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPRValuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [455 370 131 25],'string','Rload',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPcutoff_fValue  = uicontrol('Parent',figure1,'Style','edit','Position',...
                      [455 295 144 25],'string','',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPcutoff_fValuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [455 320 131 25],'string','Center f',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPBWValue  = uicontrol('Parent',figure1,'Style','edit','Position',...
                      [455 235 144 25],'string','',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPBWValuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [455 265 131 25],'string','3-dB BW',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPLPHPCalc  = uicontrol('Parent',figure1,'Style','pushbutton','Position',...
                      [455 205 131 25],'string','Calculate',...
                     'backgroundcolor','g','fontsize',13,'enable','on',...
                     'foregroundcolor','k','callback',@CalculateBP);
                 
hBPC1Valuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [630 260 145 25],'string','C||=',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPL1Valuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [630 230 145 25],'string','L||=',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPC2Valuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [630 200 145 25],'string','C--=',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
hBPL2Valuetext  = uicontrol('Parent',figure1,'Style','text','Position',...
                      [630 170 145 25],'string','L--=',...
                     'backgroundcolor','w','fontsize',13,'enable','on',...
                     'foregroundcolor','k');
                 
                 
                 
                 
function CalculateLPHP(source,eventdat)
    try
    P= str2num(get(hPrototypeValue,'string'))
    R= str2num(get(hRValue,'string'))
    f= str2num(get(hcutoff_fValue,'string'))
    debug=0;
    
    C=P/(2*pi*f*R);
    set(hC1Valuetext,'string',sprintf('C=%e',C))
    
    L=P*R/(2*pi*f);
    set(hL1Valuetext,'string',sprintf('L=%e',L))
    catch
        msgbox('error in inputs')
    end
end



function CalculateBP(source,eventdat)
    try
        
    P= str2num(get(hBPPrototypeValue,'string'))
    R= str2num(get(hBPRValue,'string'))
    f= str2num(get(hBPcutoff_fValue,'string'))
    BW=str2num(get(hBPBWValue,'string'))
    
    Cp=P/(2*pi*R*BW)
    set(hBPC1Valuetext,'string',sprintf('C||=%e',Cp))
    
    Lp=R*BW/(2*pi*f^2*P)
    set(hBPL1Valuetext,'string',sprintf('L||=%e',Lp))
    
    Cs=BW/(2*pi*f^2*P*R)
    set(hBPC2Valuetext,'string',sprintf('C--=%e',Cs))
    
    Ls=R*P/(2*pi*BW)
    set(hBPL2Valuetext,'string',sprintf('L--=%e',Ls))
    catch
        msgbox('error in inputs')
    end
    debug=0;

end

                 
end                